# Site settings
title: Grails Nicaragua
email: amakenadog@gmail.com
description: "Comunidad del framework grails en Nicaragua."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
