# Site settings
title: Grails Nicaragua
email: grailsnicaragua@gmail.com
description: "Comunidad framework grails en Nicaragua."
baseurl: ""
url: "http://yourdomain.com"

# Build settings
markdown: kramdown
permalink: pretty
